# === Main Configuration ===
model_name: "gemma3:1b"
prompt_path: "unfair_tos/prompts/8-way_prompt_v1.docx"
similarity_threshold: 90

# === OpenAI Client Configuration ===
openai:
  api_key: "ollama"
  base_url: "http://localhost:11434/v1"

# === Dataset Configuration ===
dataset:
  name: "lex_glue"
  config: "unfair_tos"
  split: "test"
  text_field: "text"
  label_field: "labels"
  eval_samples: 1607
  output_csv: "data/unfair_tos_data/test_rag_results.csv"

# === MLflow Configuration (Optional) ===
# You can set the tracking URI via environment variable
# export MLFLOW_TRACKING_URI=http://localhost:5000
# or define it here if you prefer.
mlflow:
  tracking_uri: "file:./mlruns"

rag:
  prompt_path: "prompts/classification_prompt.txt"
  persist_dir: "./data/unfair_tos_data/unfair_tos_embeddings_train_val"
  llm_model: "gemma3:1b"
  embed_model: "sentence-transformers/all-MiniLM-L6-v2"
  similarity_top_k: 3
  response_mode: "compact"
  request_timeout: 3600
  match_threshold: 90

experiment_name: "exp"